# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -ldflags "-X github.com/noqqe/serra/src/serra.Version=`git describe --tags`"  -v serra.go
    sources:
      - "src/serra/**/*.go"
      - "serra.go"
    generates:
      - "./serra"

  default:
    cmds:
      - task: build

