# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -ldflags "-X main.buildstamp=`date -u '+%F'` -X main.githash=`git rev-parse HEAD` -X main.version=git"  -v serra.go
    sources:
      - "src/serra/**/*.go"
      - "serra.go"
    generates:
      - "./serra"

  default:
    cmds:
      - task: build

